[tool.poetry]
name = "repl_python3_cli-phazed"
version = "0.1.0"
description = ""
authors = ["unixc <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
xintool = "^0.0.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
